# ============================================================================
# PORTFOLIO REPOSITORY
# ============================================================================
# This file was auto-generated on: 2026-01-28 16:49:58 WAT
# It contains asynchronous functions for managing access to the database
# in a MongoDB database using FastAPI.
#
# DO NOT EDIT THIS FILE MANUALLY - RE-RUN THE GENERATOR INSTEAD. OR IF YOU WANT TO EDIT JUST ADD LEAVE OTHER FUNCTIONS THE WAY YOU MET THEM
# ============================================================================

from pymongo import ReturnDocument
from core.database import db
from fastapi import HTTPException,status
from typing import List,Optional
from schemas.portfolio import PortfolioUpdate, PortfolioCreate, PortfolioOut

async def create_portfolio(portfolio_data: PortfolioCreate) -> PortfolioOut:
    portfolio_dict = portfolio_data.model_dump()
    result =await db.portfolios.insert_one(portfolio_dict)
    result = await db.portfolios.find_one(filter={"_id":result.inserted_id})
    returnable_result = PortfolioOut(**result)
    return returnable_result

async def get_portfolio(filter_dict: dict) -> Optional[PortfolioOut]:
    try:
        result = await db.portfolios.find_one(filter_dict)

        if result is None:
            return None

        return PortfolioOut(**result)

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching portfolio: {str(e)}"
        )
    
async def get_portfolios(filter_dict: dict = {},start=0,stop=100) -> List[PortfolioOut]:
    try:
        if filter_dict is None:
            filter_dict = {}

        cursor = (db.portfolios.find(filter_dict)
        .skip(start)
        .limit(stop - start)
        )
        portfolio_list = []

        async for doc in cursor:
            portfolio_list.append(PortfolioOut(**doc))

        return portfolio_list

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching portfolios: {str(e)}"
        )
async def update_portfolio(filter_dict: dict, portfolio_data: PortfolioUpdate) -> PortfolioOut:
    result = await db.portfolios.find_one_and_update(
        filter_dict,
        {"$set": portfolio_data.model_dump(exclude_none=True)},
        return_document=ReturnDocument.AFTER
    )
    if result is None:
        return None
    returnable_result = PortfolioOut(**result)
    return returnable_result

async def delete_portfolio(filter_dict: dict):
    return await db.portfolios.delete_one(filter_dict)


async def update_portfolio_fields(filter_dict: dict, updates: dict) -> Optional[PortfolioOut]:
    if not updates:
        return None
    result = await db.portfolios.find_one_and_update(
        filter_dict,
        {"$set": updates},
        return_document=ReturnDocument.AFTER,
    )
    if result is None:
        return None
    return PortfolioOut(**result)
